export const fieldsOptions = [
  { value: "esocial", label: "E-social" },
  { value: "enrolment", label: "Matrícula" },
  { value: "sales_code", label: "Código de vendas" },
  { value: "timecode", label: "Código de ponto" },
  { value: "worker_name", label: "Nome" },
  { value: "function_name", label: "Função" },
  { value: "turn_name", label: "Turno" },
  { value: "cost_center_name", label: "Centro de custo" },
  { value: "department_name", label: "Setor" },
  { value: "admission_date", label: "Data de admissão" },
  { value: "gender", label: "Gênero" },
  { value: "civil_status", label: "Estado civil" },
  { value: "street", label: "Logradouro" },
  { value: "street_number", label: "Número" },
  { value: "street_complement", label: "Complemento" },
  { value: "neighborhood", label: "Bairro" },
  { value: "cep", label: "CEP" },
  { value: "city", label: "Cidade" },
  { value: "state", label: "estado" },
  { value: "phone", label: "Telefone" },
  { value: "mobile", label: "Celular" },
  { value: "emergency_number", label: "Número de emergência" },
  { value: "bank", label: "Banco" },
  { value: "bank_agency", label: "Agência do banco" },
  { value: "bank_account", label: "Conta bancária" },
  { value: "resignation_date", label: "Data de desligamento" },
  { value: "resignation_reason_id", label: "Motivo do desligamento" },
  { value: "picture", label: "Foto" },
  { value: "has_children", label: "Possui filhos" },
  { value: "children_data", label: "Dados dos filhos" },
  { value: "military_cert_number", label: "Certificado militar" },
  { value: "votant_title", label: "Título de eleitor" },
  { value: "votant_zone", label: "Zona eleitoral" },
  { value: "votant_session", label: "Sessão eleitoral" },
  { value: "cnh", label: "CNH" },
  { value: "cnh_category", label: "Categoria CNH" },
  { value: "cnh_emition_date", label: "Data de emissão da CNH" },
  { value: "cnh_valid_date", label: "Validade da CNH" },
  { value: "first_job", label: "Primeiro emprego" },
  { value: "was_employee", label: "Já foi colaborador" },
  { value: "union_contribute_current_year", label: "Contribuição sindical (ano atual)" },
  { value: "receiving_unemployment_insurance", label: "Recebendo seguro-desemprego" },
  { value: "previous_experience", label: "Experiência anterior" },
  { value: "month_wage", label: "Salário mensal" },
  { value: "hour_wage", label: "Salário por hora" },
  { value: "journey_wage", label: "Salário por jornada" },
  { value: "transport_voucher", label: "Vale transporte" },
  { value: "transport_voucher_quantity", label: "Qtd. vale transporte" },
  { value: "diary_workjourney", label: "Jornada diária" },
  { value: "week_workjourney", label: "Jornada semanal" },
  { value: "month_workjourney", label: "Jornada mensal" },
  { value: "experience_time", label: "Tempo de experiência" },
  { value: "nocturne_hours", label: "Horas noturnas" },
  { value: "dangerousness", label: "Periculosidade" },
  { value: "unhealthy", label: "Insalubridade" },
  { value: "wage_payment_method", label: "Forma de pagamento" },
]